specVersion: 1.0.0
name: lucky-subql
version: 0.0.4
runner:
  node:
    name: "@subql/node"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: This SubQuery project can be use as a starting point for Astar network
repository: "https://github.com/GuiGou12358/lucky-subql"
schema:
  file: ./schema.graphql
network:
  chainId: "0xddb89973361a170839f80f152d2e9e38a376a5a7eccefcade763f46a8e567019"
  endpoint: "wss://rpc.shibuya.astar.network"
  
  #chainId: "0xf1cf9022c7ebb34b162d5b5e34e705a5a740b2d0ecc1009fb89023e62a488108"
  #endpoint: "wss://shiden.api.onfinality.io/ws?apikey=f3f17916-0fb2-456c-9f23-93ebf374f68c"  
  #endpoint: "wss://rpc.shiden.astar.network"
  dictionary: "https://api.subquery.network/sq/subquery/shiden-dictionary"
  
  #chainId: "0x9eb76c5184c4ab8679d2d5d819fdf90b9c001403e9e17da2e14b6d8aec4029c6"
  #endpoint: "wss://astar.api.onfinality.io/public-ws"
  #dictionary: "https://api.subquery.network/sq/subquery/astar-dictionary"
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 2674210
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: bondAndStake
          kind: substrate/EventHandler
          filter:
            module: dappsStaking
            method: BondAndStake
        - handler: unbondAndUnstake
          kind: substrate/EventHandler
          filter:
            module: dappsStaking
            method: UnbondAndUnstake
        - handler: nominationTransfer
          kind: substrate/EventHandler
          filter:
            module: dappsStaking
            method: NominationTransfer
        - handler: reward
          kind: substrate/EventHandler
          filter:
            module: dappsStaking
            method: Reward
        - handler: newDappStakingEra
          kind: substrate/EventHandler
          filter:
            module: dappsStaking
            method: NewDappStakingEra
  - kind: substrate/Wasm
    startBlock: 2674210
    processor:
      file: ./node_modules/@subql/substrate-wasm-processor/dist/bundle.js
      options:
        abi: luckyRaffle
        contract: bT55Mwv3h9gkpY3vQgsoTbBddAEHktfgHcfgSXwFfzUtigR
    assets:
      luckyRaffle:
        file: ./metadata/lucky_raffle_metadata.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: raffleDone
          kind: substrate/WasmEvent
          filter:
            identifier: RaffleDone
  - kind: substrate/Wasm
    startBlock: 2674210
    processor:
      file: ./node_modules/@subql/substrate-wasm-processor/dist/bundle.js
      options:
        abi: rewardManager
        contract: ba7rMagiHkAYAyr8DAuMQAAkhnabPmsLEVfiJvUifxNajz9
    assets:
      rewardManager:
        file: ./metadata/reward_manager_metadata.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: pendingReward
          kind: substrate/WasmEvent
          filter:
            identifier: PendingReward
  - kind: substrate/Wasm
    startBlock: 2674210
    processor:
      file: ./node_modules/@subql/substrate-wasm-processor/dist/bundle.js
      options:
        abi: rewardManager
        contract: ba7rMagiHkAYAyr8DAuMQAAkhnabPmsLEVfiJvUifxNajz9
    assets:
      rewardManager:
        file: ./metadata/reward_manager_metadata.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: rewardsClaimed
          kind: substrate/WasmEvent
          filter:
            identifier: RewardsClaimed
            